ListifyWebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ListifyWebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ListifyWebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ListifyWebApp.Pages
{
    public class IndexModel : PageModel
    {

        public void OnGet()
        {

        }
    }
}

ListifyWebApp/Pages/Page2.cshtml.cs
using ListifyWebApp.DataAccess;
using ListifyWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ListifyWebApp.Pages
{

    
    public class Page2Model : PageModel
    {
        DatabaseContext db;

        public Page2Model(DatabaseContext db)
        {
            this.db = db;
        }

        
        [BindProperty]
        public Listify listify { get; set; }

        [BindProperty]
        public string taskDescription { get; set; }
        public List<ItemTask> items { get; set; } = new List<ItemTask>(); 

        public void OnGet()
        {
        
        }
       
        public IActionResult OnPostAddListify(string[] task)
        {

            for (int i = 0; i < task.Length; i++)
            {
                ItemTask itemTask = new ItemTask()
                {
                    TaskDescription = task[i]
                };

                items.Add(itemTask);

            }
            listify.tasks = items;
            db.Listify.Add(listify);
            for (int i = 0; i < items.Count; i++)
            {
                db.Task.Add(items[i]);
            } 
            db.SaveChanges();
            return RedirectToPage("Page3");
        }
    }
}

ListifyWebApp/Pages/Page3.cshtml.cs
using ListifyWebApp.DataAccess;
using ListifyWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ListifyWebApp.Pages
{
    
    public class Page3Model : PageModel
    {
        DatabaseContext db;

        public Page3Model(DatabaseContext db)
        {
            this.db = db;
        }
        [BindProperty]
        public Listify listify { get; set; }
        [BindProperty]
        public List<Listify> Listifies { get; set; }

        [BindProperty]
        public ItemTask itemTask { get; set; }
       
        public void OnGet()
        {
            Listifies = db.Listify.Include(t => t.tasks).ToList();
        }
        
        public void OnPost(int id)
        {
            Response.Redirect("Update?Id=" + id);
            
        }
    }
}

ListifyWebApp/Pages/Update.cshtml.cs
using ListifyWebApp.DataAccess;
using ListifyWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using System.Linq;

namespace ListifyWebApp.Pages
{
    
    public class UpdateModel : PageModel
    {
        DatabaseContext db;

        [BindProperty]
        public Listify listify { get; set; }

        [BindProperty]
        public List<ItemTask> Tasks { get; set; } = new List<ItemTask>();

        [BindProperty]
        public ItemTask itemTask { get; set; }
        [BindProperty]
        public string info { get; set; }


        public int ListifyId;

        public UpdateModel(DatabaseContext db)
        {
            this.db = db;
           
        }

        public void OnGet(int Id)
        {
            
            ListifyId = Id;
            listify = db.Listify
                     .Include( l => l.tasks)
                     .SingleOrDefault(l => l.Id == Id);
            Tasks = listify.tasks;
            
        }
        public ActionResult OnPostDeleteListify(int Id, string infostring, string saveListify, string deleteListify) 
        {
            if (saveListify != null)
            {
                Listify listify = db.Listify.SingleOrDefault(l => l.Id == Id);
                if (listify != null)
                {
                    listify.Name = infostring;
                    db.Listify.Update(listify);
                    db.SaveChanges();
                    return RedirectToPage("Page3");
                }
            }
            if (deleteListify != null)
            {
                Listify listify = db.Listify.Include(l => l.tasks).SingleOrDefault(l => l.Id == Id);
                if (listify != null)
                {
                    db.Remove(listify);
                    db.SaveChanges();
                }
                return RedirectToPage("Page3");
            }

            return RedirectToPage("Page3");
        }
        public ActionResult OnPost(int id, string info, string save, string delete)
        {
            if (save != null) {
                ItemTask item = db.Task.SingleOrDefault(t => t.Id == id);
                if (item != null)
                {
                    item.TaskDescription = info;
                    db.Task.Update(item);
                    db.SaveChanges();
                    return RedirectToPage("Page3");
                }
            }
            if (delete != null)
            {
                ItemTask item = db.Task.SingleOrDefault(t => t.Id == id);
                if(item != null)
                {
                    db.Remove(item);
                    db.SaveChanges();
                }
                return RedirectToPage("Page3");
            }
            
            return RedirectToPage("Page3");


        }
    }
}

ListifyWebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<link rel="stylesheet" href="~/css/Index.css" />



<div class="wrapper">
    <div class="static-txt">TO</div>
    <ul class="dynamic-txts">
        <li><span>DO</span></li>
        <li><span>MAKE</span></li>
        <li><span>SEE</span></li>
        <li><span>GET</span></li>
    </ul>
</div>

ListifyWebApp/Pages/Page2.cshtml
@page
@model ListifyWebApp.Pages.Page2Model
@{
   
}
<link href="~/css/Page2.css" rel="stylesheet" />
<div class="divForAddList"> 
<form method="post"  asp-page-handler="AddListify">
        
    <div class="inputForTask">
       <input asp-for="@Model.listify.Name" type="text" placeholder="List name:">
    </div>
    <div id="placeholderForTasks"></div>
    <button id="addTaskButton">Add task</button>
    <button id="submitButton" type="submit">Submit</button>

</form>
</div>

<script src="~/js/site.js"></script>
    

ListifyWebApp/Pages/Page3.cshtml
@page
@model ListifyWebApp.Pages.Page3Model
@{

}
<link href="~/css/Page3.css" rel="stylesheet" />
<div class="divForAddList">

    @foreach (var listify in Model.Listifies)
    {
       <div class="inputForTask">
          <form method="post" asp-route-id="@listify.Id">
             <button id="floatMe" type="submit">Edit</button>
             <div><p>@listify.Name</p></div>
                <ol>
                    @foreach (Models.ItemTask item in listify.tasks)
                    {
                        <div>
                              <li ><p>@item.TaskDescription</p></li>
                        </div>
                    }
                </ol>
          </form>
        </div>
    }
</div>

ListifyWebApp/Pages/Update.cshtml
@page 
@using ListifyWebApp.Models;
@model ListifyWebApp.Pages.UpdateModel
@{
}


<div class="displayboxUpdate">
    <div class ="divForTasks">
        <form method="post" asp-page-handler="DeleteListify" asp-route-id="@Model.listify.Id">
            <p>Listify: </p>
        <input id="inputName" name="infostring" asp-for="@Model.listify.Name" /> <button id="saveButton" type="submit" name="saveListify" runat="server" value="save">
            <img id="saveImg" src="~/Resorses/pics/Save-Button.png" />
        </button>
        <button id="deleteButton" type="submit" name="deleteListify" runat="server" value="delete">
            <img id="deleteImg" src="~/Resorses/pics/Trash-Bin.png" />
            </form>
    </div>
        @foreach (Models.ItemTask itemTask in @Model.Tasks)
    {
            
        <form method="post" asp-route-id="@itemTask.Id">   
           <div class="divForTasks">
             <input name="info" asp-for="@itemTask.TaskDescription">
           <button id="saveButton" type="submit" name="save" runat="server" value="save">
              <img id="saveImg" src="~/Resorses/pics/Save-Button.png" />
           </button>
           <button id="deleteButton" type="submit" name="delete" runat="server" value="delete">
               <img id="deleteImg" src="~/Resorses/pics/Trash-Bin.png" />
           </button>
           </div>
        </form>
        }
    </div>
</div>
<script src="~/js/site.js"/>
        




   